---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-stuff-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      name: kube-stuff
      labels:
        app: simple-server
    spec:
      containers:
        - name: simple-server
          image: benfen/test-images:latest
          ports:
            - containerPort: 8080