---
kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  selector:
    app: hello-world
    role: test
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-stuff-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
      role: test
      tier: backend
  template:
    metadata:
      name: kube-stuff
      labels:
        app: hello-world
        role: test
        tier: backend
    spec:
      containers:
        - name: simple-server
          image: benfen/test-images:latest
          ports:
            - containerPort: 8080
...
